server:
  port: 8086

spring:
  application:
    name: API-GATEWAY

  cloud:
    gateway:
      forwarded-headers-strategy: framework

      globalcors:
        cors-configurations:
          "[/**]":
            allowedOrigins: ["http://localhost:5173"]
            allowedMethods: [GET, POST, PUT, DELETE, OPTIONS, PATCH]
            allowedHeaders: ["*"]
            allowCredentials: true
            exposedHeaders: ["Access-Control-Allow-Origin", "Access-Control-Allow-Credentials", "Authorization"]
            maxAge: 3600

      routes:
        - id: quiz-service
          uri: lb://QUIZ-SERVICE
          predicates:
            - Path=/api/v1/quiz/**
          filters:
            - AuthenticationFilter
            - name: CircuitBreaker
              args:
                name: quizService
                fallbackUri: forward:/fallback/quiz

        - id: question-service
          uri: lb://QUESTION-SERVICE
          predicates:
            - Path=/api/v1/question/**
          filters:
            - AuthenticationFilter
            - name: CircuitBreaker
              args:
                name: questionService
                fallbackUri: forward:/fallback/question

        - id: participation-service
          uri: lb://PARTICIPATION-SERVICE
          predicates:
            - Path=/api/v1/participation/**
          filters:
            - AuthenticationFilter
            - name: CircuitBreaker
              args:
                name: participationService
                fallbackUri: forward:/fallback/participation

        - id: leaderboard-service
          uri: lb://LEADERBOARD
          predicates:
            - Path=/api/v1/leaderboard/**
          filters:
            - AuthenticationFilter
            - name: CircuitBreaker
              args:
                name: leaderboardService
                fallbackUri: forward:/fallback/leaderboard

        - id: bugreport-service
          uri: lb://BUGREPORT-SERVICE
          predicates:
            - Path=/api/v1/bugs/**
          filters:
            - AuthenticationFilter
            - name: CircuitBreaker
              args:
                name: bugReportService
                fallbackUri: forward:/fallback/bugreport

        - id: user-auth
          uri: lb://USER-AUTH
          predicates:
            - Path=/api/v1/auth/**
          filters:
            - name: CircuitBreaker
              args:
                name: userAuth
                fallbackUri: forward:/fallback/user-auth

  main:
    web-application-type: reactive

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

management:
  endpoints:
    web:
      exposure:
        include: "*"

resilience4j:
  circuitbreaker:
    instances:
      quizService:
        slidingWindowSize: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
        permittedNumberOfCallsInHalfOpenState: 2

      questionService:
        slidingWindowSize: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
        permittedNumberOfCallsInHalfOpenState: 2

      participationService:
        slidingWindowSize: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
        permittedNumberOfCallsInHalfOpenState: 2

      leaderboardService:
        slidingWindowSize: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
        permittedNumberOfCallsInHalfOpenState: 2

      bugReportService:
        slidingWindowSize: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
        permittedNumberOfCallsInHalfOpenState: 2

      userAuth:
        slidingWindowSize: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
        permittedNumberOfCallsInHalfOpenState: 2

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty.http.client: DEBUG
