server:
  port: 8088

spring:
  application:
    name: BUGREPORT-SERVICE

  data:
    mongodb:
      uri: mongodb://localhost:27017/quizzler

  mail:
    host: smtp.gmail.com
    port: 587
    username: vedanghinge070@gmail.com
    password: gigukisnnosqhzse  # Make sure to remove any accidental spaces
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
    instance-id: ${spring.application.name}:${random.uuid}

management:
  endpoints:
    web:
      exposure:
        include: "*"
