spring.application.name=participation-service
server.port=8083
#spring.data.mongodb.uri=mongodb://localhost:27017/
spring.data.mongodb.uri=mongodb+srv://quizzler:quizzler123@cluster0.wfbfhkk.mongodb.net
spring.data.mongodb.database=quizzlerDB
eureka.client.service-url.defaultZone=http://service-registry:8761/eureka
spring.cloud.compatibility-verifier.enabled=false

# Kafka Bootstrap Server
spring.kafka.bootstrap-servers=kafka:9092


# Producer config
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

# Kafka Admin (to auto-create topic)
spring.kafka.admin.auto-create=true
# Force Eureka to register using IP instead of .mshome.net
# ----- Eureka Instance -----
eureka.instance.prefer-ip-address=true
eureka.instance.instance-id=${spring.application.name}:${server.port}
eureka.instance.lease-renewal-interval-in-seconds=30
eureka.instance.lease-expiration-duration-in-seconds=90

# ----- Eureka Client -----
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.client.registry-fetch-interval-seconds=30
