# ==============================
# Application & Server Config
# ==============================
spring.application.name=leaderboard
server.port=8084

# ==============================
# MongoDB Configuration
# ==============================
spring.data.mongodb.uri=mongodb+srv://quizzler:quizzler123@cluster0.wfbfhkk.mongodb.net
spring.data.mongodb.database=quizzlerDB
# ==============================
# Eureka Client Configuration
# ==============================
eureka.client.service-url.defaultZone=http://service-registry:8761/eureka
# ----- Eureka Instance -----
eureka.instance.prefer-ip-address=true
eureka.instance.instance-id=${spring.application.name}:${server.port}
eureka.instance.lease-renewal-interval-in-seconds=30
eureka.instance.lease-expiration-duration-in-seconds=90

# ----- Eureka Client -----
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.client.registry-fetch-interval-seconds=30


# ==============================
# Kafka Consumer Configuration
# ==============================
spring.kafka.bootstrap-servers=kafka:9092
spring.kafka.consumer.group-id=leaderboard-group
spring.kafka.consumer.auto-offset-reset=earliest
# Force Eureka to register using IP instead of .mshome.net
